---
title: "MA615_Assignment2"
author: "Jiahao Xu"
date: "September 23, 2018"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1.Exercises in R for Data Science 3.5.1(2,3)
```{r}
#3.5.1(2)What do the empty cells in plot with facet_grid(drv ~ cyl) mean? How do they relate to this plot?
library(ggplot2)
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = drv, y = cyl))
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = drv, y = cyl))+facet_grid(drv ~ cyl)
# The empty cells in facet_grid(drv~cyl) mean that there are no combination of two variables in those rows and columns.


#3.5.1(3)What plots does the following code make? What does . do?
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(drv ~ .)

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  facet_grid(. ~ cyl)
# If we do not want to facet in the rows or columns dimension, use a . instead of a variable name
```
2. Exercises in R for Data Science 3.6.1(6),
```{r}
#3.6.1(6)Recreate the R code necessary to generate the following graphs
library(ggplot2)

graph1<-ggplot(data=mpg)+geom_point(mapping = aes(x = displ, y = hwy,size=class))+geom_smooth(mapping = aes(x = displ, y = hwy,se = FALSE))
graph2<-ggplot(data=mpg)+geom_point(mapping = aes(x = displ, y = hwy,size=class))+geom_smooth(mapping = aes(x = displ, y = hwy,group=drv,se = FALSE))
graph3<-ggplot(data=mpg)+geom_point(mapping = aes(x = displ, y = hwy,color=drv,size=class))+geom_smooth(mapping = aes(x = displ, y = hwy,color=drv,se = FALSE))
graph4<-ggplot(data=mpg)+geom_point(mapping = aes(x = displ, y = hwy,color=drv,size=class))+geom_smooth(mapping = aes(x = displ, y = hwy,se = FALSE))
graph5<-ggplot(data=mpg)+geom_point(mapping = aes(x = displ, y = hwy,color=drv,size=class))+geom_smooth(mapping = aes(x = displ, y = hwy,linetype=drv,se = FALSE))
graph6<-ggplot(data=mpg)+geom_point(mapping = aes(x = displ, y = hwy,color=drv,size=class))
par(mfrow=c(3,2))
graph1
graph2
graph3
graph4
graph5
graph6
```

3.Exercises in R for Data Science 5.2.4(1,2,3,4)
```{r}
#5.2.4(1)
#1.Had an arrival delay of two or more hours
library(nycflights13)
library(tidyverse)
filter(flights, arr_delay >= 120)
#2.Flew to Houston (IAH or HOU)
filter(flights,dest %in% c("IAH", "HOU"))
#3.Were operated by United, American, or Delta
filter(flights, carrier %in% c("AA", "DL", "UA"))
#4.Departed in summer (July, August, and September)
filter(flights, month %in% c(7:9))
#5.Arrived more than two hours late, but didn’t leave late
filter(flights, arr_delay > 120&dep_delay <= 0)
#6.Were delayed by at least an hour, but made up over 30 minutes in flight
filter(flights, dep_delay >= 60&(dep_delay - arr_delay > 30))
#7.Departed between midnight and 6am (inclusive)
filter(flights, dep_time >= 0 & dep_time <= 600)


#5.2.4(2)Another useful dplyr filtering helper is between(). What does it do? Can you use it to simplify the code needed to answer the previous challenges?
# between is used to express the interval in the &(and) situation.
filter(flights, between(dep_time, 0, 600))

#5.2.4(3)How many flights have a missing dep_time? What other variables are missing? What might these rows represent?
sum(is.na(flights$dep_time))
sum(is.na(flights$sched_dep_time))
sum(is.na(flights$dep_delay))
sum(is.na(flights$arr_time))
sum(is.na(flights$sched_arr_time))
sum(is.na(flights$arr_delay))
sum(is.na(flights$carrier))
map_dbl(flights, ~ sum(is.na(.x)))

#5.2.4(4)Why is NA ^ 0 not missing? Why is NA | TRUE not missing? Why is FALSE & NA not missing? Can you figure out the general rule? (NA * 0 is a tricky counterexample!)

## Every NA^0=1.NA|TRUE always equals to TRUE by the definition of or. FALSE & NA can always be tested TRUE or FALSE.
```
